name: KarmaMM
version: '${project.version}'
main: karmadev.mcpl.karmamm.nlkarmamm.NLKarmaMM
api-version: 1.18
depend: [ Vault ]
authors: [ KarmaDev ]
description: Causes the mobs to drop money when killed by players.
commands:
  kmmreload:
    aliases: []